# Generated by Django 5.2 on 2025-04-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_product_image_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='digtial',
            field=models.BooleanField(default=False),
        ),
    ]
