# Generated by Django 5.2 on 2025-04-14 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_product_digtial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='digtial',
            new_name='digital',
        ),
    ]
