# Generated by Django 5.2 on 2025-04-15 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreAuth', '0002_alter_customer_user'),
        ('Store', '0005_rename_digtial_product_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CoreAuth.seller'),
        ),
    ]
