# Generated by Django 5.2 on 2025-04-18 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_orderstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderStatus',
        ),
    ]
