# Generated by Django 5.2 on 2025-04-18 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreAuth', '0002_alter_customer_user'),
        ('Store', '0009_delete_orderstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statuschoice', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete')], default='pending', max_length=10)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoreAuth.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoreAuth.seller')),
            ],
        ),
    ]
