# Generated by Django 5.2 on 2025-04-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0011_orderstatus_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
