# Generated by Django 5.2 on 2025-04-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0012_alter_orderstatus_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
