# Generated by Django 5.2 on 2025-04-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0013_orderstatus_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('seller', models.CharField(max_length=255)),
                ('statusorder', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete')], default='pending', max_length=10)),
            ],
        ),
    ]
