# Generated by Django 5.2 on 2025-04-19 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreAuth', '0002_alter_customer_user'),
        ('Store', '0014_trackshipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackshipment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.product'),
        ),
        migrations.AlterField(
            model_name='trackshipment',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoreAuth.seller'),
        ),
    ]
