# Generated by Django 5.2 on 2025-04-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0015_alter_trackshipment_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackshipment',
            name='statusorder',
            field=models.CharField(choices=[('pending', 'Pending'), ('prepared', 'Prepared'), ('canceled', 'Canceled')], default='pending', max_length=10),
        ),
    ]
