# Generated by Django 5.2 on 2025-04-20 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreAuth', '0002_alter_customer_user'),
        ('Store', '0016_alter_trackshipment_statusorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackshipment',
            name='statusorder',
        ),
        migrations.AddField(
            model_name='trackshipment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CoreAuth.customer'),
        ),
        migrations.AddField(
            model_name='trackshipment',
            name='orderstatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Store.orderstatus'),
        ),
    ]
