# Generated by Django 5.2 on 2025-04-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0017_remove_trackshipment_statusorder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackshipment',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='trackshipment',
            name='orderstatus',
        ),
        migrations.AddField(
            model_name='trackshipment',
            name='statusorder',
            field=models.CharField(choices=[('pending', 'Pending'), ('prepared', 'Prepared'), ('canceled', 'Canceled')], default='pending', max_length=10),
        ),
    ]
