# Generated by Django 5.2 on 2025-04-20 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0018_remove_trackshipment_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackshipment',
            old_name='statusorder',
            new_name='shipmentstatus',
        ),
        migrations.AddField(
            model_name='trackshipment',
            name='orderstatus',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Store.orderstatus'),
            preserve_default=False,
        ),
    ]
