# Generated by Django 5.2 on 2025-04-20 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0019_rename_statusorder_trackshipment_shipmentstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackshipment',
            name='orderstatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Store.orderstatus'),
        ),
    ]
