# Generated by Django 5.2 on 2025-04-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0021_alter_trackshipment_orderstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackshipment',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
