# Generated by Django 5.2 on 2025-04-21 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CoreAuth", "0002_alter_customer_user"),
        ("Store", "0023_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingaddress",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="CoreAuth.seller",
            ),
        ),
    ]
