# Generated by Django 5.2 on 2025-04-21 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CoreAuth", "0002_alter_customer_user"),
        ("Store", "0024_shippingaddress_seller"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderstatus",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="CoreAuth.customer",
            ),
        ),
    ]
