# Generated by Django 5.2 on 2025-04-22 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CoreAuth", "0002_alter_customer_user"),
        ("Store", "0025_alter_orderstatus_customer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shippingaddress",
            name="seller",
        ),
        migrations.AlterField(
            model_name="orderstatus",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="CoreAuth.customer"
            ),
        ),
        migrations.AlterField(
            model_name="trackshipment",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="CoreAuth.customer"
            ),
        ),
    ]
